"""OPTIONAL parser for ``bin/namelist_doc.txt`` (generated by ``HICAR -v --all``).

This file is gitignored, so it is usually absent. When present it is used to
*enrich* / cross-check the source-derived schema, never as the primary source.

Block format::

     ------------------------------------------------------------------
     Namelist Variable:           version
         Namelist Group:.........|General
         Description:............|(-) Version of the model
         Default Value:..........|v2.1
     ------------------------------------------------------------------
"""

from __future__ import annotations

import re

_SEP = re.compile(r"^\s*-{10,}\s*$")
_VARNAME = re.compile(r"^\s*Namelist Variable:\s*(\S+)\s*$")
_FIELD = re.compile(r"^\s*([A-Za-z][A-Za-z ]+?):\.*\|(.*)$")
_LEAD_MARKER = re.compile(r"^\s*\([^)]*\)\s*")


def _normalize_field(label: str) -> str:
    return label.strip().lower().replace(" ", "_")


def parse_doc(text: str) -> dict[str, dict]:
    """Parse the doc file into {option_name: {field: value}}."""
    out: dict[str, dict] = {}
    cur: dict | None = None
    last_field: str | None = None
    for raw in text.splitlines():
        if _SEP.match(raw):
            cur = None
            last_field = None
            continue
        mv = _VARNAME.match(raw)
        if mv:
            cur = {"name": mv.group(1)}
            out[mv.group(1)] = cur
            last_field = None
            continue
        if cur is None:
            continue
        mf = _FIELD.match(raw)
        if mf:
            field = _normalize_field(mf.group(1))
            cur[field] = mf.group(2).strip()
            last_field = field
        elif last_field:
            # continuation of a multi-line field (e.g. description)
            cur[last_field] = (cur[last_field] + "\n" + raw.strip()).strip()
    return out


def clean_description(desc: str) -> str:
    """Strip the leading ``(...)`` nest/units marker the doc prepends."""
    return _LEAD_MARKER.sub("", desc).strip()
