"""Assemble a namelist from the schema, with optional scheme selections.

``mode='full'``    -> every group + option at its default, each documented.
``mode='minimal'`` -> core groups, and within them only options that must be
                      set (empty default), scheme selectors, or user overrides.
"""

from __future__ import annotations

from ..kb import Knowledge
from ..models import NmlType
from ..nml.writer import emit_group, format_value

# Canonical group ordering (matches HICAR's --gen-nml output intent).
GROUP_ORDER = [
    "General", "Domain", "Forcing", "Physics",
    "MP_Parameters", "LT_Parameters", "ADV_Parameters", "PBL_Parameters",
    "SFC_Parameters", "CU_Parameters", "LSM_Parameters", "SM_Parameters",
    "RAD_Parameters", "Wind", "Output", "Restart", "Time_Parameters",
]

MINIMAL_GROUPS = {"General", "Domain", "Forcing", "Physics", "Output"}
SELECTORS = {"mp", "pbl", "lsm", "rad", "conv", "water", "wind", "adv", "sfc", "sm"}


def _ordered_groups(kn: Knowledge) -> list[str]:
    present = kn.list_groups()
    ordered = [g for g in GROUP_ORDER if g in present]
    ordered += [g for g in present if g not in ordered]
    return ordered


def _first_line(text: str) -> str:
    return text.splitlines()[0].strip() if text else ""


def generate_namelist(
    kn: Knowledge,
    mode: str = "full",
    selections: dict[str, str] | None = None,
    overrides: dict[str, str] | None = None,
) -> str:
    selections = {k: v for k, v in (selections or {}).items() if v}
    overrides = overrides or {}
    schema = kn.schema

    chunks: list[str] = []
    header = [
        "! HICAR namelist generated by hicar-mcp",
        f"! mode: {mode}   |   HICAR version: {kn.version.get('hicar_version', '?')}",
        "! Edit paths/dates before running. See `./HICAR --gen-nml` for the authoritative template.",
        "",
    ]
    chunks.append("\n".join(header))

    for group in _ordered_groups(kn):
        if mode == "minimal" and group not in MINIMAL_GROUPS:
            continue
        block = schema.group_blocks.get(group, group.lower())
        opts = sorted(kn.options_in_group(group), key=lambda o: o.name.lower())
        lines: list[str] = []
        for opt in opts:
            value = None
            if opt.name in overrides:
                value = overrides[opt.name]
            elif opt.name in selections:
                value = selections[opt.name]
            elif opt.name in SELECTORS and opt.name in (selections or {}):
                value = selections[opt.name]
            else:
                value = opt.default

            required = opt.default == "" and opt.minimum is None
            if mode == "minimal":
                keep = (
                    opt.name in overrides
                    or opt.name in selections
                    or opt.name in SELECTORS
                    or required
                )
                if not keep:
                    continue

            rendered = format_value(value, opt.inferred_type) if value != "" else "''"
            comment = _first_line(opt.description)
            suffix = f"   ! {comment}" if comment else ""
            if required and value == "":
                suffix = f"   ! REQUIRED: {comment}" if comment else "   ! REQUIRED"
            lines.append(f"    {opt.name} = {rendered}{suffix}")
        if lines:
            chunks.append(emit_group(block, lines))

    return "\n\n".join(chunks) + "\n"


def normalize_selections(kn: Knowledge, selections: dict[str, str]) -> dict[str, str]:
    """Validate scheme selections and resolve to canonical names."""
    out: dict[str, str] = {}
    for selector, val in selections.items():
        if not val:
            continue
        scheme = kn.resolve_scheme(selector, val)
        out[selector] = scheme.name if scheme else val
    return out
